#!/bin/sh -e

libdir="/Users/huanghe/Desktop/chat/nghttp2/lib"
if [ -d "$libdir/.libs" ]; then
    libdir="$libdir/.libs"
fi

export CGO_CFLAGS="-I/Users/huanghe/Desktop/chat/nghttp2/lib/includes -I/Users/huanghe/Desktop/chat/nghttp2/lib/includes"
export CGO_LDFLAGS="-L$libdir"
export LD_LIBRARY_PATH="$libdir"
export GODEBUG=cgocheck=0
"$@"
